services:

  # Frontend SvelteKit
  frontend:
    image: node:22-alpine
    container_name: assistia-frontend
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    volumes:
      - ./src:/usr/src/app
    networks:
      - appwrite
    labels:
      - "traefik.enable=true"
      - "traefik.constraint-label-stack=appwrite"
      - "traefik.docker.network=appwrite"
      - "traefik.http.services.frontend.loadbalancer.server.port=5173"
      - "traefik.http.routers.frontend_http.entrypoints=appwrite_web"
      - "traefik.http.routers.frontend_http.rule=Host(`app.localhost`)"
      - "traefik.http.routers.frontend_http.priority=10"
      - "traefik.http.routers.frontend_https.entrypoints=appwrite_websecure"
      - "traefik.http.routers.frontend_https.rule=Host(`app.localhost`)"
      - "traefik.http.routers.frontend_https.priority=10"
      - "traefik.http.routers.frontend_https.tls=true"

volumes:
  minio_data:

    # Note : le subnet "appwrite" est déjà déclaré dans le docker-compose.yml d'Appwrite
